### ISSUE TITLE
Crash after a few frames?

### ISSUE THREAD

**Issue by MarsVard** [y4nnick/android_streaming#1]
Hi I'm using your sample and I noticed it crashes with a memory exception after a few frames.

Have you noticed it too? is there a fix?

**Comment by y4nnick** [comment]
Which phone are you using? Could you provide the stacktrace?

**Comment by IzabellaConigliaro** [comment]
Hey, mine is crashing too. I have an Galaxy S4 with Android 5.0.1
I don't have the stacktrace right now, but it always crashes when I hit the record button :/

**Comment by IzabellaConigliaro** [comment]
Process: com.example.yannick.olay1, PID: 17664
                  java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:308)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:585)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                      at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1694)
                      at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                      at com.example.yannick.olay1.RecordActivity.initRecorder(RecordActivity.java:185)
                      at com.example.yannick.olay1.RecordActivity.startRecording(RecordActivity.java:292)
                      at com.example.yannick.olay1.RecordActivity.onClick(RecordActivity.java:558)
                      at android.view.View.performClick(View.java:5184)
                      at android.view.View$PerformClick.run(View.java:20910)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:5942)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by y4nnick** [comment]
It seams that you didn't imported javacpp correct, take a look at https://github.com/bytedeco/javacv/issues/133 to resolve the UnsatisfiedLinkError

**Comment by y4nnick** [comment]
I will close this here, since it is a import problem and not related to the actual code here
